language: ruby
rvm:
  - 2.2.5
  - 2.3.5

sudo: false
  
before_script:
  - rake test
  
script:
  - rake deploy

branches:
  only:
    - master
    - develop
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer