language: ruby
rvm:
  - 2.2.0
  - 2.3.0

sudo: false

cache: bundler

before_script:
  - chmod +x ./scripts/ciBuild
  - bundle install
  - gem install awesome_bot
  - gem update --system
  
script:
  - ./scripts/ciBuild

branches:
  only:
    - master
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
 
