language: ruby
rvm:
  - 2.2.0
  - 2.3.0

sudo: false
  
before_script:
  - chmod +x ./scripts/ciBuild
  
script:
  - ./scripts/ciBuild

branches:
  only:
    - master
    - develop
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  

after_success:
