# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Developers of Future
email: dofemailhere
github: DevOfFuture
facebook: DevOfFuture
twitter: DevOfFuture
description: "Now is the most advanced humanity is, and the most advanced we’ll ever be. Now is a very fleeting concept... It was here the second you started reading the sentence, now it’s gone! And now it’s here again! Now is present with us for as long as humankind exists."
baseurl: ""
url: "https://developersoffuture.github.io"

# Build settings
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  members:

gems:
  - jekyll-feed
  - jekyll-seo-tag
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules