# DOF
title: Developers of Future
email: dofemailhere
github: DevOfFuture
facebook: DevOfFuture
twitter: DevOfFuture
description: "Now is the most advanced humanity is, and the most advanced we’ll ever be. Now is a very fleeting concept... It was here the second you started reading the sentence, now it’s gone! And now it’s here again! Now is present with us for as long as humankind exists."
baseurl: ""
url: "https://devoffuture.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

collections:
  members:

gems:
  - jekyll-feed
  - jekyll-seo-tag
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules