#!/usr/bin/env bash
set -e # halt script on error

# bundle exec jekyll build
# echo "Checking the links, files and folders in _site"
# bundle exec jekyll doctor
# bundle exec htmlproofer ./_site --disable-external

echo "Testing if all links are working or not"
awesome_bot README.md index.md --allow-redirect --white-list https://devoffuture.github.io,https://linkedin.com,https://github.com
