#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
echo "Checking the links, files and folders in _site"
bundle exec htmlproofer ./_site
# bundle exec htmlproofer ./_site --disable-external